project:
  type: website
  output-dir: docs

website:
  title: "Uriah Daugaard"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: pubs.qmd
        text: Publications & Reviewing
      - href: talks.qmd
        text: Talks
      - href: teach.qmd
        text: Teaching
      # - href: cv.qmd
      #   text: CV      "{{< ai cv >}} to be added"  
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: [flatly, _variables_flatly.scss]
      dark: [darkly, _variables_darkly.scss]
    css: styles.css
    toc: true
    grid:
      body-width: 900px

    
editor: visual


