project:
  type: website
  output-dir: docs

website:
  title: "Uriah Daugaard"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: pubs.qmd
        text: Publications
      - href: teach.qmd
        text: Teaching
      - href: talks.qmd
        text: Talks
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      light: [sandstone, _variables_light.scss]
      dark: [sandstone, _variables_dark.scss]
    css: styles.css
    toc: true
    
    
editor: visual

